---
sample_app_version: "{{ sample_app_version_to_deploy | default('0.0.1') }}"
gdrive_url: 'https://drive.google.com/uc?export=download&id='
apps:
  - name: kitchensink
    extension: war
    version: "0.0.1"
    url: "{{ gdrive_url }}1QLfgvLBb_hU6FPH4RWBK8RASgeWzJuFC"
app_dir: /opt/apps/
wfly_version: 19.0.0.Final
workdir: /opt/wildfly/
wfly_zipfile: "wildfly-{{ wfly_version }}.zip"
wfly_download_url: https://download.jboss.org/wildfly/{{ wfly_version }}/{{ wfly_zipfile }}
keycloak_adapter_version: 9.0.3
keyclodk_download_url: https://downloads.jboss.org/keycloak/{{ keycloak_adapter_version }}/adapters/keycloak-oidc/keycloak-wildfly-adapter-dist-{{ keycloak_adapter_version }}.tar.gz
java:
  home: "{{ override_widlfy_jvm | default('/usr/lib/jvm/java-1.8.0') }}"
wildfly:
  home: "{{ workdir }}/wildfly-{{ wfly_version }}/"
  user: wildfly
  group: wildfly
  bind_addr: "{{ override_wildfly_bind_addr | default(ansible_nodename) }}"
  port_range_offset: 0
  config:
    base: standalone-ha.xml
    name: wfly
  basedir_prefix: /var/run/wfly-
  min_mem: 64m
  max_mem: 512m
  metaspace_size: 96m
  metaspace_maxsize: 256m
mysqlconfig:
  db_name: wildfly
  user:
    name: wildfly
    password: wildfly
# can't use a structure for the jdbc_driver because of the interpolation between variables.
jdbc_driver_module_dir: "{{ wildfly.home }}/modules/com/mysql/main"
jdbc_driver_version: "{{ override_mysql_jdbc_driver_version | default('8.0.26') }}"
jdbc_driver_jar_filename: "mysql-connector-java-{{ jdbc_driver_version }}.jar"
jdbc_driver_jar_url: "https://github.com/deewhyweb/eap-quickstarts/raw/7.4.x/kitchensink/modules/com/mysql/main/mysql-connector-java-8.0.26.jar"
jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
jdbc_driver_module_name: 'com.mysql'
ansible_distribution: Fedora
jcliff_rules_dir: /usr/share/jcliff/rules
keycloak_auth_client: admin-cli
keycloak_admin_user: admin
keycloak_admin_password: "redhat1!"
keycloak_realm: 3trains
keycloak_url: "{{ keycloak_3trains_url | default('http://localhost:8080') }}"
keycloak_client: 3trains
