---
- assert:
    that:
      - wildfly_home is defined
      - jboss_cli_query is defined
    quiet: true

- set_fact:
    wildfly_admin_port: "{{ cli_port | default('9990') }}"
    wildfly_admin_host: "{{ cli_host | default('localhost') }}"

- set_fact:
    jboss_cli: "{{ wildfly_home }}/bin/jboss-cli.sh -c --controller={{ wildfly_admin_host }}:{{ wildfly_admin_port }}"

- block:
    - name: "Run CLI query {{ jboss_cli_query }} on {{ cli_host }}:{{ cli_port }}"
      command: >
        {{ jboss_cli }} "--command={{ jboss_cli_query }}"
      args:
        chdir: "{{ wildfly_home }}"
      register: jboss_cli_results
      changed_when: false
  rescue:
    - debug:
        msg: "CLI query {{ jboss_cli_query }} failed {{ jboss_cli_results.stdout }}"
