---
- name: "Ensures JCliff version is appropriate"
  yum:
    name: jcliff-2.12.8
    state: present

- name: "Fine tuning configuration: {{ instance_name | default('localhost') }}"
  jcliff:
    wfly_home: "{{ wildfly.home }}"
    rule_file: roles/wildfly/files/custom/
    timeout: 7000
    management_port: "{{ wildfly_instance_management_port }}"
    components:
      - system_properties:
        - name: JBOSS_ID
          value: "{{ instance_name }}"
      - deployments:
          - name: "{{ demo_app_dest | basename }}"
            path: "{{ demo_app_dest }}"
            replace_runtime_name_regex: "{{ (demo_app_dest | basename).split('-')[0] }}-.*"
      - drivers:
          - driver_name: mysql
            driver_module_name: com.mysql
            driver_class_name: com.mysql.cj.jdbc.Driver
      - datasources:
          - name: "mysql"
            jndi_name: "java:/jdbc/mysql"
            connection_url: "jdbc:mysql://192.168.122.154:3306/{{ mysqlconfig.db_name }}"
            driver_name: mysql
            user_name: "{{ mysqlconfig.user.name }}"
            password: "{{ mysqlconfig.user.password }}"
      - modcluster:
          proxy:
            - name: default
              proxies:
                - proxy1
  environment:
    JAVA_HOME: "{{ java.home }}"
