---

- set_fact:
    required_packages:
    - zip
    - unzip
    # - gcc
    # - redhat-rpm-config
    - procps-ng
    - initscripts
    - "{{ jvm_package | default('java-1.8.0-openjdk-devel') }}"
    - firewalld

- name: "Ensures required packages are installed"
  include_role:
    name: fastpackages
  vars:
    packages_list: "{{ required_packages }}"

- name: enable and start the firewalld service
  become: yes
  systemd:
    name: firewalld
    enabled: yes
    state: started
