---
- assert:
    that:
      - nb_instances is defined
    quiet: true

- set_fact:
    service_name: "{{ override_instance_prefix | default('wfly-') }}{{ item }}"
  when: item is defined

- set_fact:
    service_name: "wfly"
  when: not service_name is defined

- block:
  - command: "systemctl status {{ service_name }}"
    register: wfly_status_res
    changed_when: false
  rescue:
    - debug:
        msg: "Error when requested status on {{ service_name }}"
      when: debug_status is defined

- block:
    - set_fact:
        status_result: "{{ ansible_nodename }} : service {{ service_name }} is running"
      when:
        - wfly_status_res.rc == 0

    - set_fact:
        status_result: "{{ ansible_nodename }} : service {{ service_name }} is NOT running"
      when:
        - wfly_status_res.rc != 0

    - set_fact:
        status_report: "{{ status_report }} + ['{{ status_result }}']"
  when:
    - wfly_status_res is defined
