---
- assert:
    that:
      - wildfly is defined
      - wildfly.config is defined
      - wildfly.config.name is defined
      - wildfly.basedir_prefix is defined
      - item is defined
    quiet: true

- set_fact:
    instance_name: "{{ wildfly.config.name }}-{{ item }}"

- block:
  - name: "Stop Wildfly instance {{ instance_name }}"
    service:
      name: "{{ instance_name }}"
      state: stopped
  rescue:
    - debug:
        msg: "Service {{ instance_name }} has already been removed."
