- name: "Install mysql and relate packages"
  include_role:
    name: fastpackages
  vars:
    packages_list: "{{ mysqldb.packages_list }}"

- stat:
    path: "{{ mysqldb.mysqldata }}/pg_hba.conf"
  register: mysql

- name: Make sure pymysql is present
  become: true 
  pip:
    name: pymysql
    state: present

- name: "Ensure the mysql service is running"
  service:
    name: mysqld
    state: started
    enabled: yes

- name: "Create database"
  community.mysql.mysql_db:
    name: "{{ mysqldb.db.name }}"
    state: present

- name: "Create user for database"
  community.mysql.mysql_user:
    host: "%"
    name: "{{ mysqldb.db.user }}"
    password: "{{ mysqldb.db.user }}"
    priv: '*.*:ALL'
    state: present