---
- name: Playbook to demonstrate use of fastpackage role
  hosts: wildfly
  tasks:
    - name: Fast package 
      include_role:
        name: fastpackages
      vars:
        packages_list: 
          - zip
          - unzip 
          - vim-enhanced 
          - emacs
