---
- name: Playbook for Wildfly Hosts
  hosts: wildfly
  tasks:

    - set_fact:
        nb_instances: "{{ (nb_instance_by_node | default(2) | int ) }}"

    - name: Wildfly Role
      include_role:
        name: wildfly
        tasks_from: uninstall_wfly_instance.yml
