---
- name: "Wildfly compliance to Common Criteria"
  hosts: wildfly
  become: yes
  vars:
    wildfly_user: wildfly
    wildfly_group: wildfly
    wildfly:
      workdir: /opt/wildfly/
      download_base_url: https://download.jboss.org/wildfly/
      version: 19.0.0.Final
    wildfly_home: "{{ wildfly.workdir }}/wildfly-{{ wildfly.version }}"
    wildfly_config_base: standalone.xml
    java_home: '/usr/lib/jvm/java-1.8.0'
    java_version: '1.8'
    jdk_id: openjdk
    jboss_home: "{{ wildfly_home }}"
    override_jboss_cli_controller_port: "{{ 9990 + 100 }}"
  collections:
    - middleware_automation.jcliff
  roles:
    - wildfly_common_criteria
  tasks:
